Revert "chore(ci): Remove repository check from setup action"
This reverts commit 315f5ca13e7b6dcfe55709e3973e4f42b9a55773.

diff --git a/.github/actions/setup/action.yml b/.github/actions/setup/action.yml
--- a/.github/actions/setup/action.yml
+++ b/.github/actions/setup/action.yml
@@ -47,8 +47,13 @@ runs:
       run: |
         if [[ -n "$REGISTRY_URL" ]]; then
           echo "url=$REGISTRY_URL" >> $GITHUB_OUTPUT
-        elif [[ -n "$REGISTRY_TOKEN" ]]; then
-          echo "url=https://common.repositories.cloud.sap/artifactory/api/npm/build.releases.npm/" >> $GITHUB_OUTPUT
+        elif [[ "$REPO" == "SAP/ai-sdk-js" || "$REPO" == "SAP/cloud-sdk-js" ]]; then
+          if [[ -n "$REGISTRY_TOKEN" ]]; then
+            echo "url=https://common.repositories.cloud.sap/artifactory/api/npm/build.releases.npm/" >> $GITHUB_OUTPUT
+          else
+            echo "::error::The input 'registry-token' is required when 'registry-url' is not provided."
+            exit 1
+          fi
         else
           echo "url=https://registry.npmjs.org" >> $GITHUB_OUTPUT
         fi
